### ISSUE TITLE
Integration unpublish error

### ISSUE THREAD

**Issue by ana-r-goncalves-alb** [srinandan/integrationcli#129]
When I was trying to unpublish an integration version using the command described in the documentation (https://github.com/srinandan/integrationcli/blob/main/docs/integrationcli_integrations_versions_unpublish.md), I got the following error:

<p>The requested URL <code>/v1/projects/[project]/locations/[region]/integrations/unpub_test/versions/cce94056-4ae1-4472-90e8-9a614222e82b:deactivate</code> was not found on this server.  <ins>That’s all we know.</ins>

After reading the current documentation for the API, I discovered that the flag used to unpublish an integration version should be **unpublish** instead of **deactivate** (https://cloud.google.com/apigee/docs/reference/apis/integrations/rest/v1/projects.locations.products.integrations.versions/unpublish).

**Comment by srinandan** [comment]
Thank you for creating this issue. I have created a fix for it. We will publish a new release in a day or two.

**Comment by srinandan** [comment]
Can you please try [v0.65.1-beta](https://github.com/srinandan/integrationcli/releases/tag/v0.65.1-beta)?

**Comment by ana-r-goncalves-alb** [comment]
Tested and it's now working! 
Thank you for the quick response

**Comment by srinandan** [comment]
Thank you, closing this ticket for now.
