### ISSUE TITLE
Unable to fetch and install integrationcli

### ISSUE THREAD

**Issue by jose-reis-alb** [srinandan/integrationcli#136]
Hello,

Today when running download integrationcli , i get the error:

Downloading integrationcli_v0.65 from https://github.com/srinandan/integrationcli/releases/download/v0.65/integrationcli_v0.65_Linux_x86_64.zip ...

https://github.com/srinandan/integrationcli/releases/download/v0.65/integrationcli_v0.65_Linux_x86_64.zip is not found, please specify a valid INTEGRATIONCLI_VERSION and TARGET_ARCH

when looking further , i found that this line returns a version that does not exists:

# Determine the latest INTEGRATIONCLI version by version number ignoring alpha, beta, and rc versions.
if [ "${INTEGRATIONCLI_VERSION}" = "" ] ; then
  INTEGRATIONCLI_VERSION="$(curl -sL https://github.com/srinandan/integrationcli/releases/latest | \
                  grep -i release | grep -o 'v[0-9]\.[0-9]*' | head -1)"
  INTEGRATIONCLI_VERSION="${INTEGRATIONCLI_VERSION##*/}"
fi

is trying to fetch version 0.65 when only 0.65-beta exists.
We have a script that checks for new versions when launching a runner.

Can you help?
Apreciate all the hard work.

**Comment by srinandan** [comment]
My apologies. I have created a patch that should fix this. I will merge this fix in a bit and that should fix the download

**Comment by srinandan** [comment]
Please let me know if this fixed the problem

**Comment by srinandan** [comment]
I am moving this repo to [GoogleCloudPlatform](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit). Please open issues there.
