### ISSUE TITLE
Can't create service account

### ISSUE THREAD

**Issue by cmgpbint** [srinandan/integrationcli#55]
When running ` integrationcli token gen -a serviceaccount.json` having 2 issues,

1. I had to create manually @ ~./.integrationcli
2. Got an error and do not know which file is wrong, config, server response .. other
`Error: error reading config file: unexpected end of JSON input`

**Comment by srinandan** [comment]
`integrationcli` doesn't allow you to create a service account. If you must use a CLI to create a service account, you must use gcloud.

`integrationcli` can be used in one of two ways:

- Generate a user token like this: `token=$(gcloud auth print-access-token)` and use it in subsequent `integrationcli` commands by passing it like this `integrationcli -t $token`
- Create a service account via gcloud and generating a token from it.

To create a service account via gcloud, please use the following commands:
```
gcloud iam service-accounts create some-account-name --display-name="My Service Account" --project $project
gcloud iam service-accounts keys create serviceaccount.json --iam-account=some-account-name@$project.iam.gserviceaccount.com --project $project
``` 

The resulting `serviceaccount json` file can be used with `integrationcli` like the command you tried.

You must also give this service account permissions, you'll need something like this:
```
gcloud iam service-accounts add-iam-policy-binding some-account-name@$project.iam.gserviceaccount.com --member='serviceAccount:some-account-name@${project}.iam.gserviceaccount.com' --role='roles/integrations.apigeeIntegrationAdminRole' --project $project
```

**Comment by cmgpbint** [comment]
thank you for the quick reply! Will try to replicate your instructions!

**Comment by cmgpbint** [comment]
Quick update

With the `token=$(gcloud auth print-access-token)` did not have luck, maybe policies restriction from my organization, however the Service Account with OAuth2 worked just fine!

Thank you for help!
