### ISSUE TITLE
integration upload error in file 

### ISSUE THREAD

**Issue by cmgpbint** [srinandan/integrationcli#70]
At the current moment I'm able to download(export) the json version using the CLI Tool.

However, if I try to upload(import) the same file I got an error of invalid format.

`"code": 400, "message": "Invalid JSON payload received. Unknown name \"name\": Cannot find field.\nInvalid JSON payload received. Unknown name \"updateTime\": Cannot find field.\nInvalid JSON payload received. Unknown name \"createTime\": Cannot find field.\nInvalid JSON payload received. Unknown name \"lastModifierEmail\": Cannot find field.\nInvalid JSON payload received. Unknown name \"triggerConfigs\": Cannot find field.\nInvalid JSON payload received. Unknown name \"taskConfigs\": Cannot find field.\nInvalid JSON payload received. Unknown name \"integrationParameters\": Cannot find field.", "status": "INVALID_ARGUMENT"...`

I tried to use import action from UI with the same file and works fine.

**Comment by srinandan** [comment]
I suspect you tried the following commands:

```
integrationcli integrations versions get -n $name -v <uuid> -t $token > $name.json
```

If this assumption is true, then the correct way to upload this file is to use

```
integrationcli integrations versions patch -n $name -v <uuid> -f $name.json -t $token
```

The format for file upload is different and doesn't use the format produced by "get".

**Comment by cmgpbint** [comment]
In this particular case was the upload method, which I assume will create a new INTEGRATION with the following command

```
~/.integrationcli/bin/integrationcli integrations upload -t $TOKEN -n $INTEGRATION_NAME -p $INTEGRATION_PROJECT -r $INTEGRATION_REGION -f $INTEGRATION_FILE_LOCATION
```

I'll test with the new version and provide feedback

**Comment by srinandan** [comment]
A useful hint:

Use the preferences command to set the project and region so you don't have to add `-p` and `-r` in every command 
```
integrationcli prefs set --nocheck=true --reg=$region --proj=$project
```

Coming to upload vs get:

To use upload, the correct sequence of commands are:

```
integrationcli integrations versions download -n <name> 
```

You can use a snapshot, userLabel or the version (a uuid) to download. However, you will notice the file downloaded is a different type of JSON. 

```
integrationcli integrations versions download -n sample -s 29 -t $token > sample_ver_29.json
```

This downloads snapshot number 29.

Only the json from this command can be used with `upload`. 

```
integrationcli integrations upload -f sample_ver_29.json -n sample -t $token
```

In this case, if `sample` doesn't exist, it will be created. If it exists, then a new version will be created.

**Comment by srinandan** [comment]
I prefer using

```
integrationcli integrations versions get -n sample -v <uuid> -t $token > sample_ver_29.json
```

I'm adding support for snapshot and labels here.

If you use this to download, then use the following command for upload

```
integrationcli integrations versions create -n sample -t $token -f sample_ver_29.json
```
Since the integration already exists, a new version is automatically created.

**Comment by cmgpbint** [comment]
Thanks for feedback, it was greatly appreciated!

It was not very clear the redundancy of both methods.

I also prefered to use the **_versions_** , however it doesn't support snapshot flag ( -s )!
